[project]
name = "cmake-project"
version = "0.1.0"
description = "Add a short description here"
authors = ["Your Name <your.email@url.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
cmake-init = "cd .. && cmake-init"
configure = "sh $PIXI_PROJECT_ROOT/scripts/configure.sh"
build = { cmd = "sh $PIXI_PROJECT_ROOT/scripts/build.sh", depends-on = ["configure"] }
install = { cmd = "sh $PIXI_PROJECT_ROOT/scripts/install.sh", depends-on = ["build"] }

[dependencies]
cmake = ">=3.30.2,<4"
clang-format = ">=18.1.8,<19"
cmake-format = ">=0.6.13,<0.7"
clang-tools = ">=18.1.8,<19"
ninja = ">=1.12.1,<2"
make = ">=4.3,<5"
python = ">=3.12.4,<4"
unzip = ">=6.0,<7"
doxygen = ">=1.10.0,<2"
cppcheck = ">=2.14.2,<3"
codespell = ">=2.3.0,<3"
gxx_linux-64 = ">=13.2.0,<14"
gcc_linux-64 = ">=13.3.0,<14"
clangxx_linux-64 = ">=18,<19"
clang_linux-64 = ">=18,<19"
clangdev = ">=18.1.8,<19"
llvmdev = ">=18.1.8,<19"
sysroot_linux-64 = ">=2.28"
cuda = ">=12.6.0,<13"
spirv-tools = ">=2024.1,<2025"
ocl-icd = ">=2.3.2,<3"
ocl-icd-system = ">=1.0.0,<2"
zlib = ">=1.3.1,<2"
llvm-openmp = ">=18.1.8,<19"
boost = ">=1.85.0,<2"

[pypi-dependencies]
cmake-init = ">=0.40.7, <0.41"
