cmake_minimum_required(VERSION 3.14)

if(SCALIX_DEVELOPER_MODE AND DEFINED "SCALIX_CLANG_TIDY_COMMAND")
  set(SCALIX_CXX_CLANG_TIDY ${SCALIX_CLANG_TIDY_COMMAND}
                            ${SCALIX_CLANG_TIDY_ARGS})
  if(NOT DEFINED "AdaptiveCpp_DIR")
    include(${CMAKE_SOURCE_DIR}/cmake/add_clang_tidy_to_target.cmake)
  else()
    function(scalix_add_clang_tidy_to_library target)
      return()
    endfunction()

    function(scalix_add_clang_tidy_to_executable target)
      return()
    endfunction()
  endif()
endif()

if(NOT DEFINED "SCALIX_EXTRA_SYCL_ARGS")
  set(SCALIX_EXTRA_SYCL_ARGS "")
endif()

if(DEFINED "AdaptiveCpp_DIR")
  find_package(AdaptiveCpp REQUIRED)
  find_package(Threads REQUIRED)
  if(NOT DEFINED "SCALIX_SYCL_TARGETS")
    message(WARNING "No SYCL targets defined, using default generic SSCP mode")
    set(SCALIX_SYCL_TARGETS "generic")
  endif()
  if("${SCALIX_SYCL_TARGETS}" MATCHES "cuda\..*")
    find_package(CUDAToolkit REQUIRED)
  endif()
  set(ACPP_TARGETS "${SCALIX_SYCL_TARGETS}")
else()
  if(NOT DEFINED "SCALIX_SYCL_TARGETS")
    message(WARNING "No SYCL targets defined, using default spir64_x86_64")
    set(SCALIX_SYCL_TARGETS "spir64_x86_64")
  endif()
  set(SCALIX_CXX_FLAGS "-fsycl" "-fsycl-targets=${SCALIX_SYCL_TARGETS}"
                       "${SCALIX_EXTRA_SYCL_ARGS}")
endif()

function(configure_target_for_scalix target)
  if(DEFINED "SCALIX_CXX_FLAGS")
    target_compile_options(${target} PUBLIC ${SCALIX_CXX_FLAGS})
    target_link_options(${target} PUBLIC ${SCALIX_CXX_FLAGS})
  endif()

  if(DEFINED "AdaptiveCpp_DIR")
    target_compile_definitions(${target} PUBLIC SCALIX_ADAPTIVECPP)
    get_target_property(TARGET_SOURCES ${target} SOURCES)
    add_sycl_to_target(TARGET ${target} SOURCES ${TARGET_SOURCES})
    target_link_libraries(${target} PUBLIC Threads::Threads)
  endif()
endfunction()
